#!/usr/bin/env python3
"""Generate the error code table on hyperliquid/errors.mdx from the hip4-backend error registry.

The registry is hip4-backend's protocol/jsonschema/error.schema.json (generated there from
internal/platform/publicerror). The table lists every code the published spec in
hyperliquid/openapi.json returns, plus every realtime stream close reason.

    python3 scripts/hyperliquid_errors.py --registry ../hip4-backend/protocol/jsonschema/error.schema.json
    python3 scripts/hyperliquid_errors.py --registry ... --check   # exit 1 if the page is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "hyperliquid/openapi.json"
PAGE = ROOT / "hyperliquid/errors.mdx"
START = "{/* error-registry:start (generated by scripts/hyperliquid_errors.py; do not edit) */}\n"
END = "{/* error-registry:end */}\n"


def returned_codes(spec: dict) -> set[str]:
    """Codes named by the narrowed error responses of the published operations."""
    codes: set[str] = set()
    for item in spec["paths"].values():
        for method, operation in item.items():
            if not isinstance(operation, dict) or "responses" not in operation:
                continue
            for status, response in operation["responses"].items():
                if status >= "400":
                    codes.update(re.findall(r"^- `([A-Z0-9_]+)` \(retry", response.get("description", ""), re.M))
    return codes


def render(registry: list[dict], codes: set[str]) -> str:
    rows = ["| Code | HTTP | Stream close | Retry | Meaning |", "| --- | ---: | ---: | --- | --- |"]
    for entry in registry:
        if entry["code"] not in codes and "close" not in entry:
            continue
        rows.append(
            f"| `{entry['code']}` | {entry.get('status', '-')} | {entry.get('close', '-')} "
            f"| `{entry['retry']}` | {entry['description']} |"
        )
    return "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--registry", type=Path, required=True, help="hip4-backend protocol/jsonschema/error.schema.json")
    parser.add_argument("--check", action="store_true", help="fail if the page differs instead of writing it")
    args = parser.parse_args()

    registry = json.loads(args.registry.read_text())["x-totalis-registry"]
    spec = json.loads(SPEC.read_text())
    codes = returned_codes(spec)
    unknown = codes - {entry["code"] for entry in registry}
    if unknown:
        print(f"spec returns codes missing from the registry: {sorted(unknown)}", file=sys.stderr)
        return 1

    page = PAGE.read_text()
    head, rest = page.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + START + "\n" + render(registry, codes) + "\n" + END + tail
    if args.check:
        if updated != page:
            print(f"{PAGE.relative_to(ROOT)} is stale; run scripts/hyperliquid_errors.py", file=sys.stderr)
            return 1
        return 0
    PAGE.write_text(updated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
